export const shops = [
  { id: 1, name:"Alpha Stationery", products: "Pens, Notebooks,pencil,Markers, Folders, Markers", location: "Coimbatore" },
  { id: 2, name:"Eco Paper House", products: "Recycled Paper, Diaries, Files, Notebooks", location: "Chennai" },
  { id: 3, name:"Campus Stationers", products: "Pens, Erasers, Scales, Notebooks, Markers", location: "Erode" },
  { id: 4, name:"Paper World", products: "Files, Diaries, Folders, A4 Sheets, Notebooks", location: "Chennai" },
  { id: 5, name:"Office Essentials", products: "Pens, Files, Notebooks, Diaries, Staplers", location: "Madurai" },
  { id: 6, name:"Stationery Hub", products: "Pens, Notebooks, Pencils, Markers", location: "Palakkad" },
  { id: 7, name:"Notebook Planet", products: "Notebooks, Diaries,pencil Folders, Pens", location: "Palakkad" },
  { id: 8, name:"Bright Tech", products: "Laptops, Keyboards, Headphones, Mouse", location: "Madurai" },
  { id: 9, name: "Smart Gadgets Hub", products: "Smartphones, Chargers, Speakers, Headphones", location: "Coimbatore" },
  { id: 10, name:"Techno Zone", products: "Laptops, Mouse, Monitors, Chargers, Keyboards", location: "Trichy" },
  { id: 11, name:"Gadget World", products: "Smartphones, Laptops, Headphones, Speakers, Monitors", location: "Salem" },
  { id: 12, name: "Electronics", products: "Smartphones, Laptops, Headphones, Chargers", location: "Palakkad" },
  { id: 13, name:"Daily Needs Mart", products: "Groceries, Cleaning Items, Snacks", location: "Salem" },
  { id: 14, name:"Green Leaf Grocers", products: "Snacks, Organic Food, Cleaning Items, Vegetables", location: "Coimbatore" },
  { id: 15, name:"Home Essentials", products: "Cleaning Items, Groceries, Snacks, Toiletries", location: "Salem" },
  { id: 16, name:"QuickMart", products: "Groceries, Beverages, Snacks, Household Items", location: "Chennai" },
  { id: 17, name:"Grocery Hub", products: "Snacks, Beverages, Cleaning Items, Fresh Vegetables", location: "Palakkad" },
  { id: 18, name:"FreshMart", products: "Groceries, Snacks, Beverages, Cleaning Items", location: "Trichy" },
  { id: 19, name:"Tasty Treats", products: "Burgers, Pizzas, Sandwiches, Beverages", location: "Chennai" },
  { id: 20, name: "Healthy Bites", products: "Salads, Smoothies, Sandwiches, Juices", location: "Coimbatore" },
  { id: 21, name: "Foodie Hub", products: "Pizzas, Burgers, Pasta, Beverages", location: "Trichy" },
  { id: 22, name: " Snacks Corner", products: "Snacks, Beverages, Burgers, Sandwiches", location: "Palakkad" },
  { id: 23, name: "Snack Attack", products: "Burgers, Sandwiches, Fries, Beverages", location: "Madurai" },
  { id: 24, name: "Knowledge Academy", products: "Books, Stationery, Educational Kits", location: "Madurai" },
  { id: 25, name: "Smart Learning Center", products: "Books, Worksheets, Study Materials, Learning Kits", location: "Coimbatore" },
  { id: 26, name: "Learning Hub", products: "Books, Notebooks, Educational Games, Worksheets", location: "Palakkad" },
  { id: 27, name: "Study Smart", products: "Books, Worksheets, Notebooks, Study Kits", location: "Trichy" },
  { id: 28, name: "Creative Prints", products: "Posters, Visiting Cards, Brochures, Flyers", location: "Trichy" },
  { id: 29, name: "PrintCraft Studio", products: "Brochures, Business Cards, Posters, Flyers, Banners", location: "Coimbatore" },
  { id: 30, name: "Print Hub", products: "Business Cards, Brochures, Posters, Flyers", location: "Palakkad" }
];
