export const shops = [
  {
    id: 1,
    name: "Alpha Stationery",
    location: "Coimbatore",
    about: "A trusted stationery store in Coimbatore, offering quality pens, notebooks, pencils, and markers.",
    products: [
      { name: "Pens", storePaidAmount: 12, normalRate: 10 },
      { name: "Notebooks", storePaidAmount: 50, normalRate: 60 },
      { name: "Pencil", storePaidAmount: 5, normalRate: 10 },
      { name: "Markers", storePaidAmount: 20, normalRate: 25 },
      { name: "Books", storePaidAmount: 200, normalRate: 180 },
    ],
  },
  {
    id: 2,
    name: "Eco Paper House",
    location: "Chennai",
    about: "Eco-friendly paper products and stationery at affordable prices.",
    products: [
      { name: "Notebooks", storePaidAmount: 15, normalRate: 65 },
      { name: "Files", storePaidAmount: 35, normalRate: 40 },
      { name: "Diaries", storePaidAmount: 40, normalRate: 50 },
      { name: "Pencil", storePaidAmount: 7, normalRate: 8 },
      { name: "Markers", storePaidAmount: 22, normalRate: 28 },
    ],
  },
  {
    id: 3,
    name: "Campus Stationers",
    location: "Erode",
    about: "Supplies for students and offices, including books, pens, and markers.",
    products: [
      { name: "Pens", storePaidAmount: 15, normalRate: 10 },
      { name: "Notebooks", storePaidAmount: 20, normalRate: 70 },
      { name: "Markers", storePaidAmount: 25, normalRate: 30 },
      { name: "Books", storePaidAmount: 180, normalRate: 160 },
    ],
  },
  {
    id: 4,
    name: "Paper World",
    location: "Chennai",
    about: "Your one-stop shop for office supplies and paper products.",
    products: [
      { name: "Files", storePaidAmount: 38, normalRate: 45 },
      { name: "Notebooks", storePaidAmount: 18, normalRate: 65 },
      { name: "Diaries", storePaidAmount: 45, normalRate: 50 },
      { name: "Pencils", storePaidAmount: 6, normalRate: 5 },
      { name: "Markers", storePaidAmount: 18, normalRate: 20 },
    ],
  },
  {
    id: 5,
    name: "Bright Tech",
    location: "Madurai",
    about: "Electronics and gadgets store specializing in laptops, phones, and accessories.",
    products: [
      { name: "Laptops", storePaidAmount: 1200, normalRate: 1100 },
      { name: "Keyboards", storePaidAmount: 50, normalRate: 45 },
      { name: "Headphones", storePaidAmount: 80, normalRate: 70 },
      { name: "Smartphones", storePaidAmount: 600, normalRate: 550 },
    ],
  },
  {
    id: 6,
    name: "Smart Gadgets Hub",
    location: "Coimbatore",
    about: "Latest gadgets, smartphones, and laptop accessories at competitive prices.",
    products: [
      { name: "Smartphones", storePaidAmount: 650, normalRate: 600 },
      { name: "Chargers", storePaidAmount: 25, normalRate: 20 },
      { name: "Speakers", storePaidAmount: 75, normalRate: 70 },
      { name: "Laptops", storePaidAmount: 1150, normalRate: 1100 },
    ],
  },
  {
    id: 7,
    name: "Daily Needs Mart",
    location: "Salem",
    about: "Groceries, snacks, and household essentials for everyday needs.",
    products: [
      { name: "Groceries", storePaidAmount: 100, normalRate: 90 },
      { name: "Cleaning Items", storePaidAmount: 50, normalRate: 45 },
      { name: "Snacks", storePaidAmount: 30, normalRate: 25 },
    ],
  },
  {
    id: 8,
    name: "Green Leaf Grocers",
    location: "Coimbatore",
    about: "Fresh vegetables, organic foods, and healthy snacks for the whole family.",
    products: [
      { name: "Vegetables", storePaidAmount: 40, normalRate: 35 },
      { name: "Organic Food", storePaidAmount: 60, normalRate: 55 },
      { name: "Snacks", storePaidAmount: 25, normalRate: 20 },
    ],
  },
  {
    id: 9,
    name: "Knowledge Academy",
    location: "Madurai",
    about: "Books, stationery, and educational kits for students and learners.",
    products: [
      { name: "Books", storePaidAmount: 220, normalRate: 200  },
      { name: "Stationery", storePaidAmount: 50, normalRate: 45 },
      { name: "Educational Kits", storePaidAmount: 150, normalRate: 140 },
      { name: "Pencils", storePaidAmount: 6, normalRate: 5 },
      { name: "Markers", storePaidAmount: 22, normalRate: 20 },
    ],
  },
  {
    id: 10,
    name: "Smart Learning Center",
    location: "Coimbatore",
    about: "Educational materials, books, and study kits for students.",
    products: [
      { name: "Books", storePaidAmount: 180, normalRate: 160 },
      { name: "Worksheets", storePaidAmount: 40, normalRate: 35 },
      { name: "Study Materials", storePaidAmount: 120, normalRate: 110 },
      { name: "Notebooks", storePaidAmount: 25, normalRate: 30 },
    ],
  },
];

